// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlbplsvkhrphgcvajfcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsYnBsc3ZraHJwaGdjdmFqZmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjQwMzEsImV4cCI6MjA1ODM0MDAzMX0.-XrQNNHJx5Ki5kyqYG2042i5OQiBI3mBLxhL4TGhUPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);